name: Publish Common Setup
description: Common steps for publish workflow (checkout, tags, node, deps, validate)
inputs:
  node-version:
    description: Node.js version
    required: false
    default: '20.x'
outputs:
  validation-status:
    description: Validation status (success or failure)
    value: ${{ steps.validate.outputs.status }}
runs:
  using: composite
  steps:
    - name: Fetch tags
      shell: bash
      run: git fetch --tags --force

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://npm.pkg.github.com'

    - name: Install dependencies
      shell: bash
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}

    - name: Validate collections
      id: validate
      shell: bash
      run: |
        if npm run validate -- --output-markdown validation-comment.md; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
        fi

    - name: Upload validation results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: validation-results
        path: |
          validation-comment.md
          validation.log
          collections/
        if-no-files-found: ignore
